//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jsoto0025.SplModeling.ExtendedFeatureModels
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ExtendedFeatureModels";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"SplModeling";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"jsoto0025";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ExtendedFeatureModelsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ExtendedFeatureModelsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ExtendedFeatureModelsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ExtendedFeatureModelsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewExtendedFeatureModelsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ExtendedFeatureModelsCommandSetId), 0x0001);
	
		// Package identifier
		public const string ExtendedFeatureModelsPackageId = "8d70c3ad-35d9-4915-b68e-fcc543f64efa";
		
		// Editor factory identifier
		public const string ExtendedFeatureModelsEditorFactoryId = "db9e1501-c654-40e6-973a-45063ddc174d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ExtendedFeatureModelsModelExplorerToolWindowId = "51a19043-282b-4f9d-a7b9-d687e176fa7f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace jsoto0025.SplModeling.ExtendedFeatureModels
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ExtendedFeatureModelsCommandSetId = "df525ab0-af4c-40ab-b617-bedc00f5668c";
	}
}